version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 3080:80
    volumes:
      - ./www:/srv/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/srv/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./php.ini:/etc/php7/php.ini
    networks:
      - www
    env_file: .env
    depends_on:
      - percona

  percona:
    image: percona
    ports:
      - 33061:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - www
    env_file: .env

volumes:
  dbdata:

networks:
  www:
