version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - ${WWW_PORT}:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - phpsocket:/var/run
      - codebase:/srv/www:ro
    networks:
      - default
    depends_on:
      - mutagen
      - php

  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - phpsocket:/var/run
      - codebase:/srv/www
    networks:
      - default
    env_file:
      - ../.env
      - ./php/php.env
    environment:
      MYSQL_SERVER: percona
      SMTP_SERVER: smtpserver
    depends_on:
      - mutagen
      - percona
      - smtpserver

  percona:
    image: percona
    ports:
      - 3306
    networks:
      - default
    volumes:
      - mysql:/var/lib/mysql
      - ../backups/db/:/var/backup/
    env_file: ../.env

  smtpserver:
    image: namshi/smtp
    restart: always
    environment:
      MAILNAME: smtpserver
    ports:
      - 25:25
    networks:
      - default
    env_file: ../.env

  mutagen:
    build:
      context: mutagen
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ../www:/alpha
      - codebase:/beta

networks:
  default:

volumes:
  mysql:
  phpsocket:
  codebase:
