version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - ${WWW_PORT}:80
    volumes:
      - ../www:/srv/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - phpsocket:/var/run
    networks:
      - default
    depends_on:
      - php

  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ../../www:/srv/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - phpsocket:/var/run
    networks:
      - default
    env_file:
      - ../.env
      - ./php/php.env
    environment:
      MYSQL_SERVER: percona
      SMTP_SERVER: smtpserver
    depends_on:
      - percona
      - smtpserver


  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
    networks:
      - default
    env_file: ../.env

  percona:
    image: percona
    ports:
      - 3306
    networks:
      - default
    volumes:
      - mysql:/var/lib/mysql
      - ../backups/db/:/var/backup/
    env_file: ../.env

  smtpserver:
    image: namshi/smtp
    restart: always
    environment:
      MAILNAME: smtpserver
    ports:
      - 25:25
    networks:
      - default
    env_file: ../.env

networks:
  default:

volumes:
  mysql:
  phpsocket:
