version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - ${PORT}:80
    volumes:
      - ../www:/srv/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
    depends_on:
      - php

  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ../www:/srv/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
    env_file:
      - ../.env
      - ./php/php.env
    environment:
      MYSQL_SERVER: percona
    depends_on:
      - percona
      - mail

  percona:
    image: percona
    ports:
      - 3306
    networks:
      - www
    volumes:
      - mysql:/var/lib/mysql
      - ../backups/db/:/var/backup/
    env_file: ../.env
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8084:8080
#    networks:
#      - www
#    env_file: ../.env

  mail:
    image: namshi/smtp
    restart: always
    ports:
      - 25:25
    networks:
      - www
    env_file: ../.env

networks:
  www:

volumes:
  mysql:
