version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - ${PORT}:80
    volumes:
      - ../www:/srv/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
    depends_on:
      - php

  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ../www:/srv/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
    env_file:
      - ../.env
      - ./php/php.env
    depends_on:
      - percona

  percona:
    image: percona
    ports:
      - 33061:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - www
    env_file: ../.env

volumes:
  dbdata:

networks:
  www:
